# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Points',
            new_name='PointCount',
        ),
        migrations.RenameField(
            model_name='pointcount',
            old_name='price',
            new_name='points',
        ),
    ]
