# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='betcomment',
            name='bet',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='bet.Bet'),
        ),
    ]
