# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0002_auto_20160718_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
