# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 20:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0003_bet_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='published_date',
        ),
        migrations.AddField(
            model_name='bet',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 7, 19, 20, 15, 41, 64000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
